-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Asset')


local SET = protobuf.Descriptor();
local SET_USERNAME_FIELD = protobuf.FieldDescriptor();
local SET_PASSWORD_FIELD = protobuf.FieldDescriptor();
local SET_FILENAME_FIELD = protobuf.FieldDescriptor();
local SET_ASSETPATH_FIELD = protobuf.FieldDescriptor();
local SET_PROTOCOL_FILENAME_FIELD = protobuf.FieldDescriptor();
local ELEMENT = protobuf.Descriptor();
local ELEMENT_META = protobuf.Descriptor();
local ELEMENT_META_TYPE_FIELD = protobuf.FieldDescriptor();
local ELEMENT_META_INDEX_FIELD = protobuf.FieldDescriptor();
local ELEMENT_METAS_FIELD = protobuf.FieldDescriptor();


SET_USERNAME_FIELD.name = "username"
SET_USERNAME_FIELD.full_name = "Asset.Set.username"
SET_USERNAME_FIELD.number = 1
SET_USERNAME_FIELD.index = 0
SET_USERNAME_FIELD.label = 1
SET_USERNAME_FIELD.has_default_value = false
SET_USERNAME_FIELD.default_value = ""
SET_USERNAME_FIELD.type = 12
SET_USERNAME_FIELD.cpp_type = 9

SET_PASSWORD_FIELD.name = "password"
SET_PASSWORD_FIELD.full_name = "Asset.Set.password"
SET_PASSWORD_FIELD.number = 2
SET_PASSWORD_FIELD.index = 1
SET_PASSWORD_FIELD.label = 1
SET_PASSWORD_FIELD.has_default_value = false
SET_PASSWORD_FIELD.default_value = ""
SET_PASSWORD_FIELD.type = 12
SET_PASSWORD_FIELD.cpp_type = 9

SET_FILENAME_FIELD.name = "filename"
SET_FILENAME_FIELD.full_name = "Asset.Set.filename"
SET_FILENAME_FIELD.number = 3
SET_FILENAME_FIELD.index = 2
SET_FILENAME_FIELD.label = 1
SET_FILENAME_FIELD.has_default_value = false
SET_FILENAME_FIELD.default_value = ""
SET_FILENAME_FIELD.type = 12
SET_FILENAME_FIELD.cpp_type = 9

SET_ASSETPATH_FIELD.name = "assetpath"
SET_ASSETPATH_FIELD.full_name = "Asset.Set.assetpath"
SET_ASSETPATH_FIELD.number = 4
SET_ASSETPATH_FIELD.index = 3
SET_ASSETPATH_FIELD.label = 1
SET_ASSETPATH_FIELD.has_default_value = false
SET_ASSETPATH_FIELD.default_value = ""
SET_ASSETPATH_FIELD.type = 12
SET_ASSETPATH_FIELD.cpp_type = 9

SET_PROTOCOL_FILENAME_FIELD.name = "protocol_filename"
SET_PROTOCOL_FILENAME_FIELD.full_name = "Asset.Set.protocol_filename"
SET_PROTOCOL_FILENAME_FIELD.number = 5
SET_PROTOCOL_FILENAME_FIELD.index = 4
SET_PROTOCOL_FILENAME_FIELD.label = 1
SET_PROTOCOL_FILENAME_FIELD.has_default_value = false
SET_PROTOCOL_FILENAME_FIELD.default_value = ""
SET_PROTOCOL_FILENAME_FIELD.type = 12
SET_PROTOCOL_FILENAME_FIELD.cpp_type = 9

SET.name = "Set"
SET.full_name = "Asset.Set"
SET.nested_types = {}
SET.enum_types = {}
SET.fields = {SET_USERNAME_FIELD, SET_PASSWORD_FIELD, SET_FILENAME_FIELD, SET_ASSETPATH_FIELD, SET_PROTOCOL_FILENAME_FIELD}
SET.is_extendable = false
SET.extensions = {}
ELEMENT_META_TYPE_FIELD.name = "type"
ELEMENT_META_TYPE_FIELD.full_name = "Asset.Element.Meta.type"
ELEMENT_META_TYPE_FIELD.number = 1
ELEMENT_META_TYPE_FIELD.index = 0
ELEMENT_META_TYPE_FIELD.label = 1
ELEMENT_META_TYPE_FIELD.has_default_value = false
ELEMENT_META_TYPE_FIELD.default_value = 0
ELEMENT_META_TYPE_FIELD.type = 5
ELEMENT_META_TYPE_FIELD.cpp_type = 1

ELEMENT_META_INDEX_FIELD.name = "index"
ELEMENT_META_INDEX_FIELD.full_name = "Asset.Element.Meta.index"
ELEMENT_META_INDEX_FIELD.number = 2
ELEMENT_META_INDEX_FIELD.index = 1
ELEMENT_META_INDEX_FIELD.label = 3
ELEMENT_META_INDEX_FIELD.has_default_value = false
ELEMENT_META_INDEX_FIELD.default_value = {}
ELEMENT_META_INDEX_FIELD.type = 5
ELEMENT_META_INDEX_FIELD.cpp_type = 1

ELEMENT_META.name = "Meta"
ELEMENT_META.full_name = "Asset.Element.Meta"
ELEMENT_META.nested_types = {}
ELEMENT_META.enum_types = {}
ELEMENT_META.fields = {ELEMENT_META_TYPE_FIELD, ELEMENT_META_INDEX_FIELD}
ELEMENT_META.is_extendable = false
ELEMENT_META.extensions = {}
ELEMENT_META.containing_type = ELEMENT
ELEMENT_METAS_FIELD.name = "metas"
ELEMENT_METAS_FIELD.full_name = "Asset.Element.metas"
ELEMENT_METAS_FIELD.number = 1
ELEMENT_METAS_FIELD.index = 0
ELEMENT_METAS_FIELD.label = 3
ELEMENT_METAS_FIELD.has_default_value = false
ELEMENT_METAS_FIELD.default_value = {}
ELEMENT_METAS_FIELD.message_type = ELEMENT_META
ELEMENT_METAS_FIELD.type = 11
ELEMENT_METAS_FIELD.cpp_type = 10

ELEMENT.name = "Element"
ELEMENT.full_name = "Asset.Element"
ELEMENT.nested_types = {ELEMENT_META}
ELEMENT.enum_types = {}
ELEMENT.fields = {ELEMENT_METAS_FIELD}
ELEMENT.is_extendable = false
ELEMENT.extensions = {}

Element = protobuf.Message(ELEMENT)
Element.Meta = protobuf.Message(ELEMENT_META)
Set = protobuf.Message(SET)

